### ISSUE TITLE
[v0.10 beta] Database not open when using okra-memory

### ISSUE THREAD

**Issue by raykyri** [canvasxyz/canvas#299]
Replication:
- check out https://github.com/canvasxyz/canvas/tree/raymond.okra-memory-init
- npm run dev / build
- cd packages/replicated
- npx ava debug
- Inside chrome://inspect, attach a debugger to the local instance
- Debugger will stop before the first append() operation on the log

From there you can step into the in-memory gossiplog's write() operation, which fails when calling .queue() with this error:

```
Error: Database is not open
    at maybeError (/Users/selkie/Development/canvas/node_modules/abstract-level/abstract-level.js:806:27)
    at MemoryLevel.get (/Users/selkie/Development/canvas/node_modules/abstract-level/abstract-level.js:282:9)
    at MemoryStore.get (file:///Users/selkie/Development/canvas/node_modules/@canvas-js/okra-memory/lib/store.js:9:34)
    at MemoryTree.getNode (file:///Users/selkie/Development/canvas/node_modules/@canvas-js/okra/lib/store.js:57:45)
    at MemoryTree.set (file:///Users/selkie/Development/canvas/node_modules/@canvas-js/okra/lib/tree.js:47:36)
    at Object.insert (file:///Users/selkie/Development/canvas/packages/gossiplog/lib/memory/index.js:95:45)
    at GossipLog.apply (file:///Users/selkie/Development/canvas/packages/gossiplog/lib/AbstractGossipLog.js:148:19)
    at async GossipLog.append (file:///Users/selkie/Development/canvas/packages/gossiplog/lib/AbstractGossipLog.js:101:9)
    at async file:///Users/selkie/Development/canvas/packages/gossiplog/lib/memory/index.js:90:32
    at async file:///Users/selkie/Development/canvas/node_modules/p-queue/dist/index.js:187:36"
```

**Comment by joeltg** [comment]
fixed with the @canvas-js/okra-memory rewrite
